# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d531110e3883b884d8c42748a372118611424707eacf2c913369260db1a891b414c24ba5a6d094421164281ce9f9a611a758abe2aaa60b115c06104e6bfbc2f3

test:
  secret_key_base: 4118e08b8d128ca83d70d60353eda0496a6d69723bb9e3d08d14c3c422eaad4c7a4a9a0054b087b806757318e5589fdb33befb60e49e4bc6ae6ddd1c9c7339d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
