# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f0ee4487265d77ef76b180c1fb395709a194f62844e12a38e20636d3bdea0fff59f2c9a9e7f8e97275dbe92388a7fb5408e776c956ed3c99d7b926016778475

test:
  secret_key_base: 7f2e1e815ce58ef10a60be52f1256a58bf3ea97397f27d303830b32ed09a3bedbb35cc403c6d2f21a9bd5ddec26e22a3dd389b289ef2d5820f97048d4634c065

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
